ReadyCollect.Web/Controllers/RCLGLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ReadyCollect.Infrastructure.Base;
using ReadyCollect.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace ReadyCollect.Web.Controllers
{
    public class RCLGLoginController : Controller
    {
        readonly ILoginService loginService;

        public RCLGLoginController(ILoginService logService)
        {
            loginService = logService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Index(UserLoginModel userInfo, string ReturnUrl = "")
        {
            if (ModelState.IsValid)
            {                
                if (userInfo != null)
                {
                    bool isLoggedIn = false;
                    int lfKey = 0;

                    if (string.IsNullOrEmpty(userInfo.CompanyId) || userInfo.CompanyId.Length <= 3)
                    {
                        ViewBag.scriptCall = "ForgotForm();";
                        return View();
                    }

                    if (userInfo.CompanyId.Substring(0, 3).ToLower() != "ar0")
                    {
                        ViewBag.scriptCall = "ForgotForm();";
                        return View();
                    }

                    if (!Int32.TryParse(userInfo.CompanyId.Substring(3), out lfKey))
                    {
                        ViewBag.scriptCall = "ForgotForm();";
                        return View();
                    }

                    userInfo.LFpKey = lfKey;
                    var user = loginService.ValidateUser(userInfo.LFpKey, userInfo.USLogin, userInfo.USPassword);

                    isLoggedIn = (user != null && user.USpKey > 0 ? true : false);

                    if (isLoggedIn)
                    {
                        var claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Name, string.Concat(user.USFirstName," ",user.USLastName, " ",user.USInitials)),
                            new Claim(ClaimTypes.Sid, user.LFpKey.ToString()),
                            new Claim(ClaimTypes.System, user.LFName),
                            new Claim(ClaimTypes.UserData, user.USpKey.ToString()),
                            new Claim(ClaimTypes.Role, user.UGName)
                        };
                        var props = new AuthenticationProperties();
                        if (userInfo.Remeberme)
                            props.ExpiresUtc = DateTime.UtcNow.AddDays(2);
                        else
                            props.ExpiresUtc = DateTime.UtcNow.AddMinutes(10);

                        var principal = new ClaimsPrincipal(new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme));

                        await HttpContext.Authentication.SignInAsync("MyCookeiAuthentication", principal, props);

                        if (!string.IsNullOrEmpty(ReturnUrl)) return Redirect(ReturnUrl);

                        return RedirectToAction("RCLGDash", "Home");
                    }
                }
            }

            ViewBag.scriptCall = "ForgotForm();";
            return View();
        }
    }
}

ReadyCollect.Web/Views/RCLGLogin/Index.cshtml
@model ReadyCollect.Model.UserLoginModel

@{
    Layout = null;
 }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>ReadyCOLLECT | User Login</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="Login Page for ReadyCOLLECT Application" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="~/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <script src="https://use.fontawesome.com/a015d6b701.js"></script>
    <link href="~/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="~/assets/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="~/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="~/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <!-- END THEME GLOBAL STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href="~/assets/pages/css/login-4.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL STYLES -->
    <!-- BEGIN THEME LAYOUT STYLES -->
    <!-- END THEME LAYOUT STYLES -->
    <link rel="shortcut icon" href="favicon.ico" />
    <style>
        .error-msg {
            color: #e02e2e;
        }
    </style>
</head>
<!-- END HEAD -->
<body class="login">
    <div class="logo">
        <a href="login_1.html">
            <img src="~/assets/global/img/readycollect_login_wht_logo.png" alt="ReadyCOLLECT Logo" />
        </a>
    </div>
    <div class="content">
        <!-- BEGIN LOGIN FORM -->
        @using (Html.BeginForm("Index", "RCLGLogin", FormMethod.Post, new { @class = "login-form" }))
        {
            @Html.AntiForgeryToken()          
            <h3 class="form-title">Login to your account</h3>
            <div class="form-group">

                @Html.Label("Company ID", "Company ID", new { @class = "control-label visible-ie8 visible-ie9" })

                <div class="input-icon">
                    <i class="fa fa-id-badge" aria-hidden="true"></i>
                    @Html.TextBoxFor(m => m.CompanyId, new { @class = "form-control placeholder-no-fix" })
                    @Html.ValidationMessageFor(m => m.CompanyId, string.Empty, new { @class = "error-msg" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Username", "Username", new { @class = "control-label visible-ie8 visible-ie9" })
                <div class="input-icon">
                    <i class="fa fa-user"></i>
                    @Html.TextBoxFor(m => m.USLogin, new { @class = "form-control placeholder-no-fix", @placeholder = "Username" })
                    @Html.ValidationMessageFor(m => m.USLogin, string.Empty, new { @class = "error-msg" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.USPassword, new { @class = "control-label visible-ie8 visible-ie9" })
                <div class="input-icon">
                    <i class="fa fa-lock"></i>
                    @Html.PasswordFor(m => m.USPassword, new { @class = "form-control placeholder-no-fix" })
                    @Html.ValidationMessageFor(m => m.USPassword, string.Empty, new { @class = "error-msg" })
                </div>
            </div>
            <div class="form-actions">
                <label class="rememberme mt-checkbox mt-checkbox-outline">
                    @Html.CheckBoxFor(m => m.Remeberme)Remember me
                    <span></span>
                </label>
                <button type="submit" class="btn red pull-right"> Login </button>


            </div>
            <div class="forget-password">
                <h4>Forgot your password ?</h4>
                <p>
                    no worries, click
                    <a href="javascript:;" id="forget-password" class="font-dark"> here </a> to reset your password.
                </p>
            </div>
        }
        <!-- END LOGIN FORM -->
        <!-- BEGIN FORGOT PASSWORD FORM -->
        <form class="forget-form" action="index.html" method="post">
            <h3>Forget Password ?</h3>
            <p> Enter your Company ID & e-mail address below to reset your password. </p>

            <div class="alert alert-danger">
                <strong>Error!</strong> Company ID or Email cannot be found. Contact your System Admin for assistance.
            </div>
            <div class="form-group">
                <div class="input-icon">
                    <i class="fa fa-id-badge" aria-hidden="true"></i>
                    <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Company ID" name="CompanyID" />
                </div>
            </div>
            <div class="form-group">
                <div class="input-icon">
                    <i class="fa fa-envelope"></i>
                    <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email" />
                </div>
            </div>
            <div class="form-actions">
                <button type="button" id="back-btn" class="btn grey btn-outline">Back </button>
                <button type="submit" class="btn red pull-right"> Submit </button>
            </div>
        </form>
        <!-- END FORGOT PASSWORD FORM -->
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>  
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" type="text/javascript" ></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    @*<script src="~/assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>*@
    <script src="~/assets/global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
    <script src="~/assets/global/plugins/backstretch/jquery.backstretch.min.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    <script src="~/assets/global/scripts/app.min.js" type="text/javascript"></script>
    <!-- END THEME GLOBAL SCRIPTS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="~/assets/pages/scripts/login-4.min.js" type="text/javascript"></script>
    <script>
       var val=@ViewBag.scriptCall;
            if (val=="ForgotForm();")
            {
                val;
            }
                function ForgotForm()
                {
                    jQuery('.login-form').hide();
                    jQuery('.forget-form').show();
                }
    </script>
       
</body>

</html>